space_apps/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weather/',include('weather.urls')),
    url(r'^$', include('weather.urls')),

]

weather/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

app_name = 'weather'

urlpatterns = [
    url(r'^getdata/', views.index),
    # defining the view for root URL
    url(r'^$', views.index, name='index'),
    url(r'^mars/',views.mars, name='mars'),
    url(r'^earth/', views.earth, name='earth'),
    url(r'^references/', views.references, name='references'),

]

weather/models.py
from django.db import models

weather/forms.py
from django import forms

class LoginForm(forms.Form):
   user = forms.CharField(max_length = 100)

weather/views.py
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from geopy.geocoders import Nominatim
import requests
import json



# disabling csrf (cross site request forgery)

def mars(request):
    template = loader.get_template('weather/mars.html')
    return HttpResponse(template.render())

def earth(request):
    template = loader.get_template('weather/earth.html')
    return HttpResponse(template.render())


def references(request):
    template = loader.get_template('weather/references.html')
    return HttpResponse(template.render())
@csrf_exempt
def index(request):
    # if post request came
    if request.method == 'POST':
        # getting values from post
        print("in if part")
        location = request.POST.get('location')
        print ("location=",location)
        geolocator = Nominatim(user_agent="as")
        loc = geolocator.geocode(location)
        latitude = loc.latitude
        longitude = loc.longitude
        # adding the values in a context variable
        capacity = 4000
        pv_power_params = dict(
            longitude=longitude,
            latitude=latitude,
            capacity = capacity,
            api_key='XtH2jWKvhFYcfRCHJkl4x3HH8LGsWIAl',
            format='json'
        )
        radiation_params = dict(
            longitude=longitude,
            latitude=latitude,
            api_key='XtH2jWKvhFYcfRCHJkl4x3HH8LGsWIAl',
            format='json'
        )

        #url = "https://api.solcast.com.au/pv_power/forecasts?longitude="+str(longitude)+"&latitude="+str(latitude)+"&capacity="+str(capacity)+"&api_key=XtH2jWKvhFYcfRCHJkl4x3HH8LGsWIAl&format=json"
        pv_power_url = "https://api.solcast.com.au/pv_power/forecasts"
        radiation_url = "https://api.solcast.com.au/radiation/forecasts"

        pv_power_resp = requests.get(url=pv_power_url, params=pv_power_params)
        radiation_resp = requests.get(url=radiation_url, params=radiation_params)

        pv_power_data = pv_power_resp.json()
        radiation_data = radiation_resp.json()
        #print(pv_power_data)
        #print(radiation_data)
        pv_tot_forecast = pv_power_data['forecasts']
        rad_tot_forecast = radiation_data['forecasts']
        json1 = json.dumps(pv_tot_forecast)
        f = open("static/weather/scripts/dict.json", "w")
        f.write(json1)
        f.close()

        print(pv_tot_forecast)
        '''file = open('out.txt','w')
        dic1=[]
        for forecast in pv_tot_forecast:
            print (forecast)
            dic1.insert(len(dic1),forecast['pv_estimate'])
        dic2=[]
        for forecast in rad_tot_forecast:
            dic2.insert(len(dic2),forecast['period_end'])


        print ("dic1="+str(dic1[0]))
        print ("dic2="+str(dic2[0]))
        if len(dic1) == len(dic2):
            print ("hola")
        diic = []

        for i in range(len(dic1)):
            dic=[]
            dic.insert(len(dic),dic1[i])
            dic.insert(len(dic),dic2[i])

            diic.insert(len(dic),dic)
        json1 = json.dumps(diic)
        f = open("dict.json", "w")
        f.write(json1)
        f.close()

'''
        file.close()

        context = {
            'latitude': latitude,
            'longitude': longitude,
        }


        # getting our showdata template

        template = loader.get_template('weather/radiation.html')

        # returing the template
        return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template('weather/index.html')
        return HttpResponse(template.render())

weather/templates/weather/earth.html
<html>
<head>
    <meta charset="UTF-8"/>
  	{% load staticfiles %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
     integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
     crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'weather/css/bootstrap.min.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="res/favicon.ico"/>
	  <title>Solarizer - Earth</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic|Work+Sans:300,400,500,600' rel='stylesheet' type='text/css'>
   <link href="{% static 'weather/css/toolkit-startup.css' %}" rel="stylesheet">

      <link href="{% static 'weather/css/application-startup.css' %}" rel="stylesheet">

	  <link rel="stylesheet" href="{% static 'weather/css/style.css' %}"/>
    <!--<script src="{% static 'weather/scripts/myearth.js' %}" type="text/javascript"></script>-->
  <script type="text/javascript">
  $( document ).ready(function() {
      console.log( "ready!" );
  });


  function time(str,dat){
    var hrs=str.substring(0,2);
    var min=str.substring(2,5);
    var yr=dat.substring(0,4);
    var mon=dat.substring(5,7);
    var date=dat.substring(7);
    min=min+30;
    if(min>60)
    {
      hrs++;min%=60;
    }
    hrs=(hrs+5);
    if(hrs>24)
    {
      date++;
      hrs=hrs%24;
    }
    if(date>30)
    {
      mon++;
    }
  }
  $.getJSON("{% static 'weather/scripts/forecasts.json' %}",function(data){
  //console.log(data);
  //var output = '<ul>';
  i=0;
  $.each(data, function(key,val){
    //output += '<li>'+ val.pv_estimate + " " + val.period_end + '</li>';
    $('#myscroll').append('<button class="btn" id="'+ i +'" onclick="advi('+i+')">'+val.period_end.substring(0,10)+" "+ val.period_end.substring(11,16) +'</button>');
    i++;
  });
  });
  function advi(id) {
    $.getJSON("{% static 'weather/scripts/forecasts.json' %}",function(data){
      console.log(data[id]);
      $('#meter').html(Math.floor(data[id].pv_estimate)+" W");
      var ener=Math.floor(data[id].pv_estimate);
      var fans=5,f=fans;
      var ac=2,a=ac;
      var cfl=5,c=cfl;
      var comp = 1, co = comp;

      var output='<ul>';
        while(cfl>0 && ener>0)
        { if(ener>20)
          { cfl--;
            ener-=20;}
          else

          break;
        }
        output += '<li class="item"><br>' +(c-cfl) + ' CFLS <br></li>';

        while(fans>0 && ener>0)
        { if(ener>100)
          { fans--;
            ener-=100;}
          else

          break;
        }
        output += '<li class="item"><br>' +(f-fans) + ' FANS <br></li>';

        while(comp>0 && ener>0)
        { if(ener>120)
          { comp--;
            ener-=120;}
          else

          break;
        }
        output += '<li class="item"><br>' +(co-comp) + ' COMPUTERS <br></li>';

              while(ac>0 && ener>0)
              { if(ener>1400)
                { ac--;
                  ener-=1400;}
                else

                break;
              }
              output += '<li class="item"><br>' +(a-ac) + ' AIR CONDITIONER <br></li>';

        output+='<ul>';
        $('#advice').html(output);
    });
  }

  </script>

</head>
<body>

  <div class="stage" id="stage">
  <div class="container py-4 fixed-top app-navbar">
  <nav class="navbar navbar-transparent navbar-padded navbar-toggleable-sm">
    <button
      class="navbar-toggler navbar-toggler-right hidden-md-up"
      type="button"
      data-target="#stage"
      data-toggle="stage"
      data-distance="-250">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand mr-auto" href="">
      <strong id="name">Solarizer</strong>
    </a>

    <div class="hidden-sm-down text-uppercase">
      <ul class="navbar-nav">
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:index' %}">Home</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:earth' %}">Earth (NREL)</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:mars' %}">Mars (HI-SEAS)</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:references' %}">References</a>
        </li>
      </ul>
    </div>
  </nav>
  </div>

  </div>

    <div class="recommend col-md-6" id="advice">

    </div>
    <div class="reading jumbotron col-md-2" id="meter">

        <p>Wattage</p>
    </div>
     <div class="scrollmenu col-md-6" id="myscroll">
     </div>
   </body>
</html>

weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'weather/res/favicon.ico' %}"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
      
        Solarizer - You are my sunshine! 
      
    </title>

    
      <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic|Work+Sans:300,400,500,600' rel='stylesheet' type='text/css'>
      <link href="{% static 'weather/css/toolkit-startup.css' %}" rel="stylesheet">

      <link href="{% static 'weather/css/application-startup.css' %}" rel="stylesheet"><!--
      <link href="../assets/css/toolkit-minimal.css" rel="stylesheet">
      <link href="../assets/css/application-minimal.css" rel="stylesheet"> -->
        

    <style>
      @media (max-width: 768px) and (-webkit-min-device-pixel-ratio: 2) {
        body {
          width: 1px;
          min-width: 100%;
          *width: 100%;
        }
        #stage {
          height: 1px;
          overflow: auto;
          min-height: 100vh;
          -webkit-overflow-scrolling: touch;
        }
      }
    </style>

  </head>


<body>


<div class="stage" id="stage">

<div class="block block-inverse block-fill-height app-header"
     style="background-image: url({% static 'weather/res/solar_panels.png' %});">

  <div class="container py-4 fixed-top app-navbar">
  <nav class="navbar navbar-transparent navbar-padded navbar-toggleable-sm">
    <button
      class="navbar-toggler navbar-toggler-right hidden-md-up"
      type="button"
      data-target="#stage"
      data-toggle="stage"
      data-distance="-250">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand mr-auto" href="">
      <!-- <img src="Res/abc.svg" height="50" width="50"> -->
      <strong style= "background-color: "white"; padding: 12px; border-radius: 4px; color: #28669F;">Solarizer</strong>
    </a>

    <div class="hidden-sm-down text-uppercase">
      <ul class="navbar-nav">
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:index' %}">Home</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:earth' %}">Earth (NREL)</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:mars' %}">Mars (HI-SEAS)</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:references' %}">References</a>
        </li>
      </ul>
    </div>
  </nav>
</div>

  <div class="block-xs-middle pb-5">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-lg-6">
          <h1 class="block-titleData frequency">Solar solutions on demand</h1>
          <p class="lead mb-4 text-muted">Stop installing bloated scripts that all track the exact same things. Install one that does everything.</p>
          <button class="btn btn-light btn-lg"><a href="{% url 'weather:earth' %}">Try it now</button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="block block-secondary app-iphone-block">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-sm-5 hidden-sm-down">
        <img class="app-iphone" src="{% static 'weather/res/dashboard.png' %}" style="width: 350px; height: 350px">
      </div>

      <div class="col-md-6 offset-md-1 col-sm-12 offset-sm-0">
        <h6 class="text-secondary text-uppercase">Rich Analytics</h6>
        <h3>Make informed decisions with historical &amp; real time data.</h3>
        <p class="lead mb-4">We combine immediate real time events with rich historical data to help answer the toughest questions about retention, growth, and engagement.</p>
        <div class="row hidden-md-down">
          <div class="col-sm-6 mb-3">
            <h5>Data frequency</h5>
            <p>We poll for data on a millisecond basis. You can react to new information in seconds rather than days. <a href="#" class="text-primary">Learn more.</a></p>
          </div>
          <div class="col-sm-6">
            <h5>Reliability &amp; uptime</h5>
            <p>We process our data across a massively distributed network of reliable servers to ensure 99.99% uptime, always. <a href="#" class="text-primary">Learn more</a>.</p>
            <br>
              </br>
            <br>
              </br>
            <br>
              </br>
            <br>
              </br>
            </p>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="block block-inverse block-secondary app-code-block">
  <div class="container">
    <div class="row app-align-center">
      <div class="col-md-5 push-md-7">
        <pre class="app-code">

<span>1</span> <span>solarDataJson</span> “What parameters do we use?”
<span>2</span>
<span>3</span>  {
<span>4</span>    "Day": {
<span>5</span>      "ID": "Vibhor sharma",
<span>6</span>      "Date": "26-09-18",
<span>7</span>      "Solar_Radiation": "1123",
<span>8</span>      "Barometric_Pressure": "30.46", 
<span>9</span>      "Humidity": "76",
<span>10</span>     "Temperature": "24",
<span>11</span>     "Wind_Direction": "151.95",
<span>12</span>     "Azimuthal": "87",
<span>13</span>     "Wind_Speed": "7.87",
<span>14</span>     "Sunrise_Sunset": "15.25",
<span>15</span>    }
<span>16</span>  }</pre>
      </div>

      <div class="col-md-6 pull-md-5">
        <h6 class="text-muted text-uppercase">Easy to use</h6>
        <h3>We'll do all the hard work</h3>
        <p class="lead mb-4 text-muted">Form based natural language queries that makes mining data easy for anyone. We use all the parameters shown beside. But thats all under the hood. You can use the form to obtain your daily usage predictions.</p>
        <button class="btn btn-secondary btn-lg btn-borderless">
          <a href="{% url 'weather:references' %}">Read our references</a>
        </button>
      </div>
    </div>
  </div>
</div>

<div class="block block-secondary app-block-marketing-grid">
  <div class="container text-xs-center">

    <div class="row mb-5">
      <div class="col-xs-10 offset-xs-1 col-sm-8 offset-sm-2 col-lg-6 offset-lg-3">
        <h6 class="text-secondary text-uppercase mb-2">Inside the machine</h6>
        <h3  class="mb-4">It’s not hard to see how solar can make your life easier every day</h3>
      </div>
    </div>

    <div class="row app-marketing-grid">
      <div class="col-md-4 px-4 mb-5">
        <img class="mb-1" src="{% static 'weather/res/startup-9.svg' %}">
        <p><strong class="text-dark">24/7 Power </strong><p class="text-dark">The Sun-grid hybrid system ensures all-day power</p></p>
      </div>
      <div class="col-md-4 px-4 mb-5">
        <img class="mb-1" src="{% static 'weather/res/startup-12.svg' %}">
        <p><strong class="text-dark">Rich calculations</strong><p class="text-dark"> Limitless ways to splice and dice your data.</p></p>
      </div>
      <div class="col-md-4 px-4 mb-5">
        <img class="mb-1" src="{% static 'weather/res/startup-11.svg' %}">
        <p><strong class="text-dark">Turnaround</strong><p class="text-dark"> Our machine learning is distributed, so it processes in seconds.</p></p>
      </div>
    </div>

  </div>
</div>

<div class="block block-bordered-lg text-center">
  <div class="container-fluid">
    <p class="lead mb-4" style="color: black;">
      <strong>Join us on this solar revolution.</strong> Sign up for a free account. <strong>Free forever!</strong>
    </p>
    <form class="form-inline d-flex justify-content-center">
      <input class="form-control mb-3" placeholder="email address">
      <input class="form-control mb-3 mx-1" type="password" placeholder="Create a Password">
      <button class="btn btn-primary mb-3">Get started</button>
    </form>
    <small class="text-muted">
      By clicking "Get started" I agree to Mochi's
      <a href="#">Terms of service</a>
    </small>
  </div>
</div>

<div class="block block-inverse app-footer">
 <div class="container">
    <div class="row">
      <div class="col-md-5 mb-5">
        <ul class="list-unstyled list-spaced">
          <li class="mb-2"><h6 class="text-uppercase">About</h6></li>
          <li class="text-muted">
             We’ve been working on Go Analytics for the better part of a decade and are super proud of what we’ve created. If you’d like to learn more, or are interested in a job, contact us anytime at <a href="mailto: themes@getbootstrap.com">themes@getbootstrap.com</a>.
          </li>
        </ul>
      </div>
      <div class="col-md-2 offset-md-1 mb-5">
        <ul class="list-unstyled list-spaced">
          <li class="mb-2"><h6 class="text-uppercase">Product</h6></li>
          <li class="text-muted">Features</li>
          <li class="text-muted">Examples</li>
          <li class="text-muted">Tour</li>
          <li class="text-muted">Gallery</li>
        </ul>
      </div>
      <div class="col-md-2 mb-5">
        <ul class="list-unstyled list-spaced">
          <li class="mb-2"><h6 class="text-uppercase">Apis</h6></li>
          <li class="text-muted">Rich data</li>
          <li class="text-muted">Simple data</li>
          <li class="text-muted">Real time</li>
          <li class="text-muted">Social</li>
        </ul>
      </div>
      <div class="col-md-2 mb-5">
        <ul class="list-unstyled list-spaced">
          <li class="mb-2"><h6 class="text-uppercase">Legal</h6></li>
          <li class="text-muted">Terms</li>
          <li class="text-muted">Legal</li>
          <li class="text-muted">Privacy</li>
          <li class="text-muted">License</li>
        </ul>
      </div>
    </div>
  </div>
</div>

</div>


    <script src="{% static 'weather/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'weather/scripts/tether.min.js' %}"></script>
    <script src="{% static 'weather/scripts/toolkit.js' %}"></script>
    <script src="{% static 'weather/scripts/application.js' %}"></script>
  </body>
</html>


weather/templates/weather/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Space apps</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />

</head>
<body>
<h1>Space apps</h1>

      <form method="post" action="/weather/getdata/">
    <table>
        <tr>
            <td>Enter your location:</td>
            <td><input type="text" name="location"/></td>
        </tr>

        <tr>
            <td>

            </td>
            <td>
                <button>Submit Form</button>
            </td>
        </tr>
    </table>
</form>

</body>
</html>

weather/templates/weather/mars.html
<html>
<head>

	<title>Solarizer - Mars</title>
	{% load staticfiles %}
	<link rel="shortcut icon" type="image/png" href="{% static 'weather/res/favicon.ico' %}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="{% static 'weather/css/toolkit-startup.css' %}" rel="stylesheet">

      <link href="{% static 'weather/css/application-startup.css' %}" rel="stylesheet"><link href='https://fonts.googleapis.com/css?family=Lora:400,400italic|Work+Sans:300,400,500,600' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="stage" id="stage">

	<div class="block block-inverse block-fill-height app-header"
	     style="background-image: url({% static 'weather/res/mars.jpg' %});">

	  <div class="container py-4 fixed-top app-navbar">
	  <nav class="navbar navbar-transparent navbar-padded navbar-toggleable-sm">
	    <button
	      class="navbar-toggler navbar-toggler-right hidden-md-up"
	      type="button"
	      data-target="#stage"
	      data-toggle="stage"
	      data-distance="-250">
	      <span class="navbar-toggler-icon"></span>
	    </button>

	    <a class="navbar-brand mr-auto" href="">

	      <strong style= "text-decoration-color: white; font-size: 1.5em; padding: 12px; border-radius: 4px">Solarizer</strong>
	    </a>

	     <div class="hidden-sm-down text-uppercase">
      <ul class="navbar-nav">
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:index' %}">Home</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:earth' %}">Earth (NREL)</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:mars' %}">Mars (HI-SEAS)</a>
        </li>
        <li class="nav-item px-1 ">
          <a class="nav-link" href="{% url 'weather:references' %}">References</a>
        </li>

      </ul>
    </div>
	  </nav>
	</div>

	  <div class="block-xs-middle pb-5">
	    <div class="container">
	      <div class="row">
	        <div class="col-sm-10 col-lg-6">
	          <h1 class="block-titleData frequency">Solar solutions on demand</h1>
	          <p class="lead mb-4 text-muted">Stop installing bloated scripts that all track the exact same things. Install one that does everything.</p>
	          <p><h1>Now for Martians!</h1></p>

	        </div>
	      </div>
	    </div>
	  </div>
</div>

<br>

<div class="block block-secondary app-iphone-block">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-md-8 hidden-sm-down">
        <img class="app-iphone" src="{% static 'weather/res/rover.jpg' %}" style="width: 700px; height: 400px">
      </div>

      <div class="col-md-4">
        <h6 class="text-secondary text-uppercase">Solar rover on Mars</h6>
        <h3>This is the means of transport on mars and it also consumes the most energy!</h3>
        <p class="lead mb-4"></p>
    </div>
</div>

<div class="block block-secondary app-iphone-block">
  <div class="container">
    <div class="row app-align-center">

      <div class="col-md-8 hidden-sm-down">
        <img class="app-iphone" src="{% static 'weather/res/station.png' %}" style="width: 625px; height: 225px">
      </div>

      <div class="col-md-4">
        <h6 class="text-secondary text-uppercase">Oxygen Chamber</h6>
        <h3>Your life revolves around this mini-world. It is a simulation of Earth on Mars. You've got to give it the most power.</h3>
        <p class="lead mb-4"></p>
    </div>
</div>
		<br><br>
		<div class="container-fluid col-md-12">

				<img src="{% static 'weather/res/timeline.png' %}">
		</div>
		<br><br>
		<section id="first-step" class="step content-100">
			<div class="container">
				<h1 class="text-center section-heading">Solar on <mark class='mark-style'>Mars</mark>?</h1>
				<hr class="tall">
				<div class="margin-top25">
					<div class="row">

						<div class="col-md-12 area step1">


							<div class="right text-center">
								<form>
									<div class="container">
										<p class="text-dark form-style">Number of rovers: </p>
										<input id="householdBDs" type="number" required value="3" min="1" max="8">
										<span>Mars-Rovers</span>
									</div>
									<br>
									<div class="container">
										<p class="form-style">Oxygen chamber size (bedrooms)</p>
										<input id="householdBDs" type="number" required value="3" min="1" max="8">
										<span>Rooms</span>
									</div>
									<div class="submit-button">
									<br>
										<button id="calculate" class="btn"> <a href="#second-step" class="button glow-button">Calculate</a>

									</div>

								</form>
							</div>

						</div>
					</div>
				</div>
				<div class='bottom-space'>
				</div>
			</div>
		</section>
		<br><br>
		<section id="second-step" class="step content-100">
			<div class="container">
				<h1 class="text-center section-heading">What you need to go solar</h1>
				<hr class="tall">
				<p class="text-center section-content">
					Based on your location and household size our ML model recommends:
				</p>
				<div class="container-fluid col-md-12 text-center">
				<br>
				<img src="{% static 'weather/res/volt_panels.png' %}">
				<br><br>
				</div>
				<div class="margin-top25">
					<div class="row">
						<div class="col-md-12 area step1 text-center">
							<div class="right">
								<form id="apply-form">
									<div class="group has-value">
										<p class="form-style">Solar panel size (sqm)</p>
										<input id="panelSize" type="text" required value="25">
										<br><br>
									</div>
									<div class="group has-value">
										<p class="form-style">Battery Packs</p>
										<input id="batteryPacks" type="text" required value="2">

										<br><br>
									</div>

									<div class="group has-value">
									    <p class="form-style">Total investment (INR)</p>
										<input id="investment" type="text" required value="30.000">
										<br><br>
									</div>
									<div class="group has-value">
										<p class="form-style">Return of investment from electricity savings</p>
										<input id="returnOfInvestment" type="text" required value="8 years">
										<br><br>
									</div>
									<div class="submit-button">
										<br>
										<button class="btn" id="tips"><a class="button glow-button" href="#final">Solar energy tips</a>
										</button>
									</div>
									<div id="solution">

									</div>
								</form>
							</div>

						</div>
					</div>
				</div>
				<div class='bottom-space'>
				</div>
			</div>
		</section>

	<script src="{% static 'weather/scripts/jquery.min.js' %}"></script>
	<script>
		var val = 0;
	</script>
	<script>
		$('#calculate').click(function(e){

			var batteryCapacity = 12; // kWh
			var batteryPrice = 6000; // USD
			var sunPerDay = 5; // h
			var panelGeneration = 0.15 // kWh
			var generatePrice = 0.3 // USD/W

			var bdInKw = 27.2586; // get from location
			var electricityPrice = 0.12 // USD/kWh

			var householdBDs = $('#householdBDs').val();
			var location = $('#location').val();

			var consume = householdBDs * bdInKw;
			var batteries = Math.floor(consume / batteryCapacity);
			$('#batteryPacks').val(batteries);
			val = batteries;

			var generateCapacity = consume / sunPerDay;

			var panelSize = generateCapacity / panelGeneration
			$('#panelSize').val(panelSize);

			var investment = batteries * batteryPrice + generateCapacity * 1000 * 71 * generatePrice;
			$('#investment').val(investment);

			var returnOfInvestment = Math.floor(investment / electricityPrice / 24 / 365);
			returnOfInvestment = Math.round(returnOfInvestment / 7);
			$('#returnOfInvestment').val(returnOfInvestment + ' years');
		});

		btn = document.getElementById("tips");
		btn.addEventListener("click", function(e){

			if(val <= 2){
				// var p = document.createElement("p");
				// p.appendChild(document.createTextNode("Low power usage!"));
				// document.appendChild(p);
				alert("Low power usage! You can use another rover");
			}
			else if(val === 3 || val === 4){
				alert("Mid-range power usage for a Martian surface!");
			}
			else if(val > 4) {
				alert("High power usage!");
			}

		});
	</script>

<!--  -->
	<script src="{% static 'weather/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'weather/scripts/tether.min.js' %}"></script>
    <script src="{% static 'weather/scripts/toolkit.js' %}"></script>
    <script src="{% static 'weather/scripts/application.js' %}"></script>
</body>
</html>-